server:
  port: 8080
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/study
logging:
  file:
    name: E:\JavaCodeIDEA\Study\IPlantTest\log\iPlant.log
  level:
    com.iPlant: info
socket:
  port: 8888

